var menu = [
   {
      "itemName":"Island Nachos",
      "cat":"app",
      "ingredients":[
         [
            "dbf5b9",
            false
         ],
         [
            "28f9b2",
            true
         ],
         [
            "19e344",
            false
         ],
         [
            "51c8c9",
            true
         ],
         [
            "a57a2e",
            true
         ],
         [
            "b2612d",
            false
         ],
         [
            "9d7634",
            false
         ],
         [
            "eb099b",
            false
         ],
         [
            "6a1dd5",
            false
         ],
         [
            "49dd5d",
            true
         ]
      ],
      "side":"None",
      "silverware":"Fork"
   },
   {
      "itemName":"Quesadilla",
      "cat":"app",
      "ingredients":[
         [
            "d3883c",
            false
         ],
         [
            "19e344",
            false
         ],
         [
            "a3ebf2",
            false
         ],
         [
            "a57a2e",
            true
         ],
         [
            "f99fb1",
            false
         ],
         [
            "7fa83",
            false
         ],
         [
            "2e2bc",
            false
         ],
         [
            "eb099b",
            false
         ],
         [
            "49dd5d",
            false
         ]
      ],
      "side":"None",
      "silverware":"Knife\/Fork"
   },
   {
      "itemName":"Cheddar Fries",
      "cat":"app",
      "ingredients":[
         [
            "54baaa",
            false
         ],
         [
            "d3e932",
            false
         ],
         [
            "19e344",
            false
         ],
         [
            "51c8c9",
            true
         ],
         [
            "1c75a6",
            true
         ],
         [
            "f99fb1",
            false
         ]
      ],
      "side":"None",
      "silverware":"Fork"
   },
   {
      "itemName":"Wings",
      "cat":"app",
      "ingredients":[
         [
            "3ede6d",
            false
         ],
         [
            "3d255",
            false
         ],
         [
            "55e848",
            false
         ],
         [
            "f16bb4",
            false
         ],
         [
            "87a247",
            false
         ]
      ],
      "side":"None",
      "silverware":"None"
   },
   {
      "itemName":"Appetizer Tiki Tenders",
      "cat":"app",
      "ingredients":[
         [
            "1c893c",
            false
         ],
         [
            "7fa83",
            false
         ],
         [
            "79dc42",
            false
         ]
      ],
      "side":"None",
      "silverware":"None"
   },
   {
      "itemName":"Jr Tiki Tenders",
      "cat":"app",
      "ingredients":[
         [
            "548a08",
            false
         ],
         [
            "87a247",
            false
         ]
      ],
      "side":"Islands Fries",
      "silverware":"None"
   },
   {
      "itemName":"Mac N Cheese",
      "cat":"gremmie",
      "ingredients":[
         [
            "663852",
            false
         ],
         [
            "87a247",
            false
         ]
      ],
      "side":"Islands Fries",
      "silverware":"Teaspoon"
   },
   {
      "itemName":"Jr Noodles & Butter",
      "cat":"gremmie",
      "ingredients":[
         [
            "d5ed77",
            false
         ],
         [
            "9c7ad5",
            false
         ],
         [
            "964192",
            false
         ],
         [
            "87a247",
            false
         ]
      ],
      "side":"Islands Fries",
      "silverware":"Fork"
   },
   {
      "itemName":"Lil Tiki Tenders",
      "cat":"gremmie",
      "ingredients":[
         [
            "991056",
            false
         ],
         [
            "87a247",
            false
         ]
      ],
      "side":"Islands Fries",
      "silverware":"None"
   },
   {
      "itemName":"Jr Quesadilla",
      "cat":"gremmie",
      "ingredients":[
         [
            "d3883c",
            false
         ],
         [
            "19e344",
            false
         ],
         [
            "87a247",
            false
         ]
      ],
      "side":"Islands Fries",
      "silverware":"None"
   },
   {
      "itemName":"Appetizer Pineapple Skewers",
      "cat":"app",
      "ingredients":[
         [
            "655e7a",
            false
         ],
         [
            "846e95",
            false
         ]
      ],
      "side":"None",
      "silverware":"None"
   },
   {
      "itemName":"Jungle Caesar w\/ Chicken",
      "cat":"salad",
      "ingredients":[
         [
            "c4c052",
            false
         ],
         [
            "cd8481",
            false
         ],
         [
            "f21f47",
            false
         ],
         [
            "ccd522",
            false
         ],
         [
            "964192",
            false
         ]
      ],
      "side":"None",
      "silverware":"Chilled Fork"
   },
   {
      "itemName":"Mainlander",
      "cat":"salad",
      "ingredients":[
         [
            "ba57e8",
            false
         ],
         [
            "ed203f",
            false
         ],
         [
            "a57a2e",
            false
         ],
         [
            "b2612d",
            false
         ],
         [
            "f99fb1",
            false
         ],
         [
            "df7bdd",
            true
         ],
         [
            "6509a2",
            false
         ]
      ],
      "side":"None",
      "silverware":"Chilled Fork"
   },
   {
      "itemName":"Garden Salad",
      "cat":"salad",
      "ingredients":[
         [
            "ba57e8",
            false
         ],
         [
            "55e848",
            false
         ],
         [
            "f21f47",
            false
         ],
         [
            "c2635f",
            false
         ],
         [
            "3dfc8e",
            false
         ],
         [
            "6509a2",
            false
         ]
      ],
      "side":"None",
      "silverware":"Chilled Fork"
   },
   {
      "itemName":"Kobb",
      "cat":"salad",
      "ingredients":[
         [
            "ba57e8",
            false
         ],
         [
            "cdd171",
            false
         ],
         [
            "f99fb1",
            false
         ],
         [
            "17003c",
            false
         ],
         [
            "ccd522",
            false
         ],
         [
            "b2612d",
            false
         ],
         [
            "69b7eb",
            false
         ],
         [
            "1c75a6",
            false
         ],
         [
            "df7bdd",
            false
         ]
      ],
      "side":"None",
      "silverware":"Chilled Fork"
   },
   {
      "itemName":"Islander",
      "cat":"salad",
      "ingredients":[
         [
            "ba57e8",
            false
         ],
         [
            "ed203f",
            false
         ],
         [
            "3dc59b",
            false
         ],
         [
            "55e848",
            false
         ],
         [
            "5d32db",
            false
         ],
         [
            "b2612d",
            false
         ],
         [
            "f99fb1",
            false
         ],
         [
            "df7bdd",
            true
         ],
         [
            "6509a2",
            false
         ]
      ],
      "side":"None",
      "silverware":"Chilled Fork"
   },
   {
      "itemName":"Wiqui Waqui",
      "cat":"salad",
      "ingredients":[
         [
            "ba57e8",
            false
         ],
         [
            "19e344",
            false
         ],
         [
            "222eab",
            false
         ],
         [
            "b44091",
            false
         ],
         [
            "b2612d",
            false
         ],
         [
            "87a247",
            false
         ],
         [
            "ccd522",
            false
         ],
         [
            "b482e5",
            false
         ],
         [
            "6be064",
            false
         ],
         [
            "f99fb1",
            false
         ]
      ],
      "side":"None",
      "silverware":"Chilled Fork"
   },
   {
      "itemName":"China Coast",
      "cat":"salad",
      "ingredients":[
         [
            "ba57e8",
            false
         ],
         [
            "55e848",
            false
         ],
         [
            "feeccf",
            false
         ],
         [
            "7c385f",
            false
         ],
         [
            "5642d3",
            false
         ],
         [
            "3dc59b",
            false
         ],
         [
            "7f30fe",
            false
         ],
         [
            "ccd522",
            false
         ],
         [
            "f99fb1",
            false
         ],
         [
            "44938d",
            false
         ]
      ],
      "side":"None",
      "silverware":"Chilled Fork"
   },
   {
      "itemName":"Sleek Greek",
      "cat":"salad",
      "ingredients":[
         [
            "cd8481",
            false
         ],
         [
            "42289e",
            false
         ],
         [
            "222eab",
            false
         ],
         [
            "b2612d",
            false
         ],
         [
            "3dfc8e",
            false
         ],
         [
            "909209",
            false
         ],
         [
            "ccd522",
            false
         ],
         [
            "3282e6",
            false
         ]
      ],
      "side":"None",
      "silverware":"Chilled Fork"
   },
   {
      "itemName":"Ketch",
      "cat":"salad",
      "ingredients":[
         [
            "ba57e8",
            false
         ],
         [
            "ed203f",
            false
         ],
         [
            "a7734b",
            false
         ],
         [
            "b2612d",
            false
         ],
         [
            "f99fb1",
            false
         ],
         [
            "6509a2",
            false
         ]
      ],
      "side":"None",
      "silverware":"Chilled Fork"
   },
   {
      "itemName":"Small Caesar",
      "cat":"salad",
      "ingredients":[
         [
            "c4c052",
            false
         ],
         [
            "cd8481",
            false
         ],
         [
            "f21f47",
            false
         ],
         [
            "964192",
            false
         ]
      ],
      "side":"None",
      "silverware":"Chilled Fork"
   },
   {
      "itemName":"Tuna Wrap",
      "cat":"other",
      "ingredients":[
         [
            "d3883c",
            false
         ],
         [
            "ba57e8",
            false
         ],
         [
            "19e344",
            false
         ],
         [
            "b2612d",
            false
         ],
         [
            "a7734b",
            false
         ],
         [
            "7fa83",
            false
         ],
         [
            "6a1dd5",
            false
         ],
         [
            "db2025",
            false
         ]
      ],
      "side":"Islands Fries",
      "silverware":"Fork\/Teaspoon"
   },
   {
      "itemName":"Chicken Club Wrap",
      "cat":"other",
      "ingredients":[
         [
            "d3883c",
            false
         ],
         [
            "ba57e8",
            false
         ],
         [
            "19e344",
            false
         ],
         [
            "b2612d",
            false
         ],
         [
            "87a247",
            false
         ],
         [
            "1c75a6",
            false
         ],
         [
            "df7bdd",
            false
         ],
         [
            "ccd522",
            false
         ],
         [
            "6be064",
            false
         ],
         [
            "7fa83",
            false
         ]
      ],
      "side":"Islands Fries",
      "silverware":"Fork\/Teaspoon"
   },
   {
      "itemName":"Charlie Tacos",
      "cat":"taco",
      "ingredients":[
         [
            "473272",
            false
         ],
         [
            "19e344",
            false
         ],
         [
            "a7734b",
            false
         ],
         [
            "2bc6f5",
            false
         ],
         [
            "b2612d",
            false
         ],
         [
            "7fa83",
            false
         ],
         [
            "6509a2",
            false
         ]
      ],
      "side":"Islands Slaw",
      "silverware":"Fork\/Teaspoon"
   },
   {
      "itemName":"California Tacos",
      "cat":"taco",
      "ingredients":[
         [
            "473272",
            false
         ],
         [
            "19e344",
            false
         ],
         [
            "2bc6f5",
            false
         ],
         [
            "3dc59b",
            false
         ],
         [
            "55e848",
            false
         ],
         [
            "5d32db",
            false
         ],
         [
            "b2612d",
            false
         ],
         [
            "f99fb1",
            false
         ],
         [
            "df7bdd",
            false
         ],
         [
            "7fa83",
            false
         ],
         [
            "6509a2",
            false
         ]
      ],
      "side":"Islands Slaw",
      "silverware":"Fork\/Teaspoon"
   },
   {
      "itemName":"Northshore",
      "cat":"taco",
      "ingredients":[
         [
            "473272",
            false
         ],
         [
            "19e344",
            false
         ],
         [
            "a57a2e",
            false
         ],
         [
            "2bc6f5",
            false
         ],
         [
            "b2612d",
            false
         ],
         [
            "7fa83",
            false
         ],
         [
            "6a1dd5",
            false
         ],
         [
            "eb099b",
            true
         ],
         [
            "49dd5d",
            true
         ]
      ],
      "side":"Ranchero Beans w\/ Cotija Cheese",
      "silverware":"Fork\/Teaspoon"
   },
   {
      "itemName":"Northshore Limited",
      "cat":"taco",
      "ingredients":[
         [
            "6726d9",
            false
         ],
         [
            "ed203f",
            false
         ],
         [
            "a57a2e",
            false
         ],
         [
            "2bc6f5",
            false
         ],
         [
            "b2612d",
            false
         ],
         [
            "7fa83",
            false
         ],
         [
            "6a1dd5",
            false
         ],
         [
            "eb099b",
            true
         ],
         [
            "49dd5d",
            true
         ]
      ],
      "side":"Ranchero Beans w\/ Cotija Cheese",
      "silverware":"Fork\/Teaspoon"
   },
   {
      "itemName":"No Blame Veggie Tacos",
      "cat":"taco",
      "ingredients":[
         [
            "6726d9",
            false
         ],
         [
            "ed203f",
            false
         ],
         [
            "bd05cd",
            false
         ],
         [
            "222eab",
            false
         ],
         [
            "5d32db",
            false
         ],
         [
            "997767",
            false
         ],
         [
            "ed22ab",
            false
         ],
         [
            "293f12",
            false
         ],
         [
            "c9f5b8",
            false
         ],
         [
            "2e2bc",
            false
         ],
         [
            "df7bdd",
            false
         ],
         [
            "7fa83",
            false
         ],
         [
            "6a1dd5",
            false
         ]
      ],
      "side":"Islands Slaw",
      "silverware":"Fork\/Teaspoon"
   },
   {
      "itemName":"Yaki",
      "cat":"taco",
      "ingredients":[
         [
            "473272",
            false
         ],
         [
            "19e344",
            false
         ],
         [
            "43c975",
            false
         ],
         [
            "aaab0f",
            false
         ],
         [
            "dd7267",
            false
         ],
         [
            "2bc6f5",
            false
         ],
         [
            "b2612d",
            false
         ],
         [
            "c6195c",
            false
         ],
         [
            "7fa83",
            false
         ],
         [
            "eb099b",
            true
         ]
      ],
      "side":"Ranchero Beans w\/ Cotija Cheese",
      "silverware":"Fork\/Teaspoon"
   },
   {
      "itemName":"Baja",
      "cat":"taco",
      "ingredients":[
         [
            "473272",
            false
         ],
         [
            "91704d",
            true
         ],
         [
            "5fb96c",
            false
         ],
         [
            "ed22ab",
            false
         ],
         [
            "67409a",
            false
         ],
         [
            "fafcf5",
            false
         ],
         [
            "c55826",
            false
         ],
         [
            "7fa83",
            false
         ],
         [
            "2e2bc",
            false
         ],
         [
            "eb099b",
            true
         ],
         [
            "49dd5d",
            true
         ]
      ],
      "side":"Ranchero Beans w\/ Cotija Cheese",
      "silverware":"Fork\/Teaspoon"
   },
   {
      "itemName":"Grilled Mahi Tacos",
      "cat":"taco",
      "ingredients":[
         [
            "6726d9",
            false
         ],
         [
            "91704d",
            true
         ],
         [
            "1ac532",
            false
         ],
         [
            "236676",
            false
         ],
         [
            "2b14a8",
            false
         ],
         [
            "50c935",
            false
         ],
         [
            "b2612d",
            false
         ],
         [
            "7fa83",
            false
         ],
         [
            "faf0ce",
            false
         ],
         [
            "2e2bc",
            false
         ],
         [
            "49dd5d",
            true
         ]
      ],
      "side":"Ranchero Beans w\/ Cotija Cheese",
      "silverware":"Fork\/Teaspoon"
   },
   {
      "itemName":"Island Fish",
      "cat":"taco",
      "ingredients":[
         [
            "6726d9",
            false
         ],
         [
            "91704d",
            true
         ],
         [
            "30cbab",
            false
         ],
         [
            "236676",
            false
         ],
         [
            "2b14a8",
            false
         ],
         [
            "50c935",
            false
         ],
         [
            "b2612d",
            false
         ],
         [
            "7fa83",
            false
         ],
         [
            "faf0ce",
            false
         ],
         [
            "2e2bc",
            false
         ],
         [
            "49dd5d",
            true
         ]
      ],
      "side":"Ranchero Beans w\/ Cotija Cheese",
      "silverware":"Fork\/Teaspoon"
   },
   {
      "itemName":"California Flyer",
      "cat":"taco",
      "ingredients":[
         [
            "fa18ef",
            false
         ],
         [
            "9fec6c",
            false
         ],
         [
            "2bc6f5",
            false
         ],
         [
            "b2612d",
            false
         ],
         [
            "3f0e18",
            false
         ],
         [
            "25d4c8",
            false
         ],
         [
            "1c75a6",
            true
         ],
         [
            "c28678",
            false
         ],
         [
            "6be064",
            false
         ],
         [
            "b9dc8a",
            false
         ]
      ],
      "side":"Islands Fries",
      "silverware":"Knife\/Fork"
   },
   {
      "itemName":"Moa Kai",
      "cat":"burger",
      "ingredients":[
         [
            "fa18ef",
            false
         ],
         [
            "9fec6c",
            false
         ],
         [
            "2bc6f5",
            false
         ],
         [
            "b2612d",
            false
         ],
         [
            "e31eee",
            false
         ],
         [
            "a7734b",
            false
         ],
         [
            "19e344",
            false
         ],
         [
            "df7bdd",
            true
         ],
         [
            "b9dc8a",
            false
         ]
      ],
      "side":"Islands Fries",
      "silverware":"Knife\/Fork"
   },
   {
      "itemName":"Wedge",
      "cat":"burger",
      "ingredients":[
         [
            "fa18ef",
            false
         ],
         [
            "9fec6c",
            false
         ],
         [
            "2bc6f5",
            false
         ],
         [
            "b2612d",
            false
         ],
         [
            "1c75a6",
            false
         ],
         [
            "19e344",
            false
         ],
         [
            "df7bdd",
            true
         ],
         [
            "b9dc8a",
            false
         ]
      ],
      "side":"Islands Fries",
      "silverware":"Knife\/Fork"
   },
   {
      "itemName":"Turkey Burger Lite",
      "cat":"burger",
      "ingredients":[
         [
            "917098",
            false
         ],
         [
            "8372bd",
            false
         ],
         [
            "2bc6f5",
            false
         ],
         [
            "222eab",
            false
         ],
         [
            "b2612d",
            false
         ],
         [
            "e54a77",
            false
         ]
      ],
      "side":"Steamed Veggies",
      "silverware":"Knife\/Fork"
   },
   {
      "itemName":"Sandpiper",
      "cat":"burger",
      "ingredients":[
         [
            "fa18ef",
            false
         ],
         [
            "9fec6c",
            false
         ],
         [
            "2bc6f5",
            false
         ],
         [
            "b2612d",
            false
         ],
         [
            "3f0e18",
            false
         ],
         [
            "1f2027",
            false
         ],
         [
            "1c75a6",
            true
         ],
         [
            "5d32db",
            false
         ],
         [
            "b9dc8a",
            false
         ]
      ],
      "side":"Islands Fries",
      "silverware":"Knife\/Fork"
   },
   {
      "itemName":"Toucan",
      "cat":"burger",
      "ingredients":[
         [
            "fa18ef",
            false
         ],
         [
            "2bc6f5",
            false
         ],
         [
            "b2612d",
            false
         ],
         [
            "3f0e18",
            false
         ],
         [
            "1f2027",
            false
         ],
         [
            "1c75a6",
            true
         ],
         [
            "aaab0f",
            false
         ],
         [
            "dd7267",
            false
         ],
         [
            "b9dc8a",
            false
         ]
      ],
      "side":"Islands Fries",
      "silverware":"Knife\/Fork"
   },
   {
      "itemName":"Shorebird",
      "cat":"burger",
      "ingredients":[
         [
            "fa18ef",
            false
         ],
         [
            "9fec6c",
            false
         ],
         [
            "2bc6f5",
            false
         ],
         [
            "b2612d",
            false
         ],
         [
            "e31eee",
            false
         ],
         [
            "3f0e18",
            false
         ],
         [
            "1f2027",
            false
         ],
         [
            "1c75a6",
            true
         ],
         [
            "df7bdd",
            true
         ],
         [
            "b9dc8a",
            false
         ]
      ],
      "side":"Islands Fries",
      "silverware":"Knife\/Fork"
   },
   {
      "itemName":"Big Wave",
      "cat":"burger",
      "ingredients":[
         [
            "fa18ef",
            false
         ],
         [
            "8372bd",
            false
         ],
         [
            "2bc6f5",
            false
         ],
         [
            "3bd9c",
            false
         ],
         [
            "b2612d",
            false
         ],
         [
            "e31eee",
            false
         ],
         [
            "3c3c2",
            false
         ],
         [
            "5fb51c",
            true
         ],
         [
            "b9dc8a",
            false
         ]
      ],
      "side":"Islands Fries",
      "silverware":"Knife\/Fork"
   },
   {
      "itemName":"Longboarder",
      "cat":"burger",
      "ingredients":[
         [
            "fa18ef",
            false
         ],
         [
            "2bc6f5",
            false
         ],
         [
            "3bd9c",
            false
         ],
         [
            "b2612d",
            false
         ],
         [
            "e31eee",
            false
         ],
         [
            "3c3c2",
            false
         ],
         [
            "5fb51c",
            true
         ],
         [
            "b9dc8a",
            false
         ]
      ],
      "side":"Islands Fries",
      "silverware":"Knife\/Fork"
   },
   {
      "itemName":"Mavericks",
      "cat":"burger",
      "ingredients":[
         [
            "fa18ef",
            false
         ],
         [
            "9fec6c",
            false
         ],
         [
            "2bc6f5",
            false
         ],
         [
            "b2612d",
            false
         ],
         [
            "e31eee",
            false
         ],
         [
            "3c3c2",
            false
         ],
         [
            "5fb51c",
            false
         ],
         [
            "df7bdd",
            true
         ],
         [
            "1c75a6",
            true
         ],
         [
            "c28678",
            false
         ],
         [
            "6be064",
            false
         ],
         [
            "b9dc8a",
            false
         ]
      ],
      "side":"Islands Fries",
      "cat":"burger",
      "silverware":"Knife\/Fork"
   },
   {
      "itemName":"Pipeline",
      "cat":"burger",
      "ingredients":[
         [
            "fa18ef",
            false
         ],
         [
            "8372bd",
            false
         ],
         [
            "2bc6f5",
            false
         ],
         [
            "3bd9c",
            false
         ],
         [
            "b2612d",
            false
         ],
         [
            "e31eee",
            false
         ],
         [
            "3c3c2",
            false
         ],
         [
            "5fb51c",
            false
         ],
         [
            "51c8c9",
            false
         ],
         [
            "b9dc8a",
            false
         ]
      ],
      "side":"Islands Fries",
      "silverware":"Knife\/Fork"
   },
   {
      "itemName":"Kilauea",
      "cat":"burger",
      "ingredients":[
         [
            "fa18ef",
            false
         ],
         [
            "e43d53",
            false
         ],
         [
            "2bc6f5",
            false
         ],
         [
            "b2612d",
            false
         ],
         [
            "b78383",
            false
         ],
         [
            "25d4c8",
            false
         ],
         [
            "1c75a6",
            true
         ],
         [
            "df7bdd",
            true
         ],
         [
            "c28678",
            false
         ],
         [
            "b9dc8a",
            false
         ]
      ],
      "side":"Islands Fries",
      "silverware":"Knife\/Fork"
   },
   {
      "itemName":"Maui",
      "cat":"burger",
      "ingredients":[
         [
            "fa18ef",
            false
         ],
         [
            "9fec6c",
            false
         ],
         [
            "2bc6f5",
            false
         ],
         [
            "3bd9c",
            false
         ],
         [
            "b2612d",
            false
         ],
         [
            "3c3c2",
            false
         ],
         [
            "1f2027",
            false
         ],
         [
            "49dd5d",
            false
         ],
         [
            "b9dc8a",
            false
         ]
      ],
      "side":"Islands Fries",
      "silverware":"Knife\/Fork"
   },
   {
      "itemName":"Hawaiian",
      "cat":"burger",
      "ingredients":[
         [
            "fa18ef",
            false
         ],
         [
            "9fec6c",
            false
         ],
         [
            "2bc6f5",
            false
         ],
         [
            "3bd9c",
            false
         ],
         [
            "b2612d",
            false
         ],
         [
            "3c3c2",
            false
         ],
         [
            "1f2027",
            false
         ],
         [
            "1c75a6",
            true
         ],
         [
            "df7bdd",
            true
         ],
         [
            "aaab0f",
            false
         ],
         [
            "dd7267",
            false
         ],
         [
            "b9dc8a",
            false
         ]
      ],
      "side":"Islands Fries",
      "silverware":"Knife\/Fork"
   },
   {
      "itemName":"Hula",
      "cat":"burger",
      "ingredients":[
         [
            "fa18ef",
            false
         ],
         [
            "9fec6c",
            false
         ],
         [
            "2bc6f5",
            false
         ],
         [
            "b2612d",
            false
         ],
         [
            "3c3c2",
            false
         ],
         [
            "1f2027",
            false
         ],
         [
            "1c75a6",
            true
         ],
         [
            "5d32db",
            false
         ],
         [
            "b9dc8a",
            false
         ]
      ],
      "side":"Islands Fries",
      "silverware":"Knife\/Fork"
   },
   {
      "itemName":"Malibu",
      "cat":"burger",
      "ingredients":[
         [
            "fa18ef",
            false
         ],
         [
            "8372bd",
            false
         ],
         [
            "2bc6f5",
            false
         ],
         [
            "3bd9c",
            false
         ],
         [
            "b2612d",
            false
         ],
         [
            "e31eee",
            false
         ],
         [
            "3c3c2",
            false
         ],
         [
            "5fb51c",
            false
         ],
         [
            "1c75a6",
            false
         ],
         [
            "b9dc8a",
            false
         ]
      ],
      "side":"Islands Fries",
      "cat":"burger",
      "silverware":"Knife\/Fork"
   },
   {
      "itemName":"Bleunami",
      "cat":"burger",
      "ingredients":[
         [
            "fa18ef",
            false
         ],
         [
            "5aba79",
            false
         ],
         [
            "2bc6f5",
            false
         ],
         [
            "222eab",
            false
         ],
         [
            "b2612d",
            false
         ],
         [
            "3c3c2",
            false
         ],
         [
            "cdd171",
            false
         ],
         [
            "1c75a6",
            true
         ],
         [
            "b9dc8a",
            false
         ]
      ],
      "side":"Islands Fries",
      "silverware":"Knife\/Fork"
   },
   {
      "itemName":"Nalu Nalu",
      "cat":"burger",
      "ingredients":[
         [
            "fa18ef",
            false
         ],
         [
            "b78a6d",
            false
         ],
         [
            "2bc6f5",
            false
         ],
         [
            "3c3c2",
            false
         ],
         [
            "1f2027",
            false
         ],
         [
            "197619",
            false
         ],
         [
            "b9dc8a",
            false
         ]
      ],
      "side":"Islands Fries",
      "silverware":"Knife\/Fork"
   },
   {
      "itemName":"Beach Bowl Chicken",
      "cat":"other",
      "ingredients":[
         [
            "fed439",
            false
         ],
         [
            "aaab0f",
            false
         ],
         [
            "222eab",
            false
         ],
         [
            "5642d3",
            false
         ],
         [
            "3dc59b",
            false
         ],
         [
            "c0659c",
            false
         ],
         [
            "84f9d7",
            false
         ],
         [
            "2729f7",
            false
         ],
         [
            "f99fb1",
            false
         ]
      ],
      "side":"None",
      "silverware":"Fork"
   },
   {
      "itemName":"Beachside Sliders",
      "cat":"app",
      "ingredients":[
         [
            "5e2536",
            false
         ],
         [
            "79d9e3",
            false
         ],
         [
            "7281b4",
            false
         ],
         [
            "ed203f",
            true
         ],
         [
            "67409a",
            false
         ],
         [
            "7fa83",
            false
         ],
         [
            "e31eee",
            false
         ],
         [
            "c28678",
            false
         ]
      ],
      "side":"None",
      "silverware":"Fork"
   },
   {
      "itemName":"Jr Wave",
      "cat":"gremmie",
      "ingredients":[
         [
            "fa18ef",
            false
         ],
         [
            "c0b552",
            false
         ],
         [
            "5fb51c",
            true
         ],
         [
            "1c75a6",
            true
         ],
         [
            "b9dc8a",
            false
         ],
         [
            "87a247",
            false
         ]
      ],
      "side":"Islands Fries",
      "silverware":"None"
   },
   {
      "itemName":"Jr Tuna",
      "cat":"gremmie",
      "ingredients":[
         [
            "fa18ef",
            false
         ],
         [
            "9fec6c",
            false
         ],
         [
            "2bc6f5",
            false
         ],
         [
            "b2612d",
            false
         ],
         [
            "e31eee",
            false
         ],
         [
            "a7734b",
            false
         ],
         [
            "19e344",
            false
         ],
         [
            "b9dc8a",
            false
         ],
         [
            "87a247",
            false
         ]
      ],
      "side":"Islands Fries",
      "silverware":"None"
   },
   {
      "itemName":"Jr Teriyaki Bowl",
      "cat":"gremmie",
      "ingredients":[
         [
            "84f9d7",
            false
         ],
         [
            "dd7267",
            false
         ],
         [
            "fed439",
            false
         ],
         [
            "c0659c",
            false
         ],
         [
            "aaab0f",
            false
         ],
         [
            "87a247",
            false
         ]
      ],
      "side":"Islands Fries",
      "silverware":"Fork"
   },
   {
      "itemName":"Lil Slider",
      "cat":"gremmie",
      "ingredients":[
         [
            "5e2536",
            false
         ],
         [
            "7281b4",
            false
         ],
         [
            "5fb51c",
            true
         ],
         [
            "87a247",
            false
         ]
      ],
      "side":"Islands Fries",
      "silverware":"None"
   },
   {
      "itemName":"Jr Grilled Chicken",
      "cat":"gremmie",
      "ingredients":[
         [
            "fa18ef",
            false
         ],
         [
            "6469ac",
            false
         ],
         [
            "5fb51c",
            true
         ],
         [
            "1c75a6",
            true
         ],
         [
            "b9dc8a",
            false
         ],
         [
            "87a247",
            false
         ]
      ],
      "side":"Islands Fries",
      "silverware":"None"
   },
   {
      "itemName":"Jr Dogger",
      "cat":"gremmie",
      "ingredients":[
         [
            "4372d5",
            false
         ],
         [
            "4e540",
            false
         ],
         [
            "ed203f",
            true
         ],
         [
            "51c8c9",
            true
         ],
         [
            "87a247",
            false
         ]
      ],
      "side":"Islands Fries",
      "silverware":"None"
   },
   {
      "itemName":"Sandcastle",
      "cat":"gremmie",
      "ingredients":[
         [
            "2ce100",
            false
         ],
         [
            "5fb51c",
            false
         ],
         [
            "87a247",
            false
         ]
      ],
      "side":"Islands Fries",
      "silverware":"None"
   },
   {
      "itemName":"Lil Sandcastle",
      "cat":"gremmie",
      "ingredients":[
         [
            "c295a",
            false
         ],
         [
            "5fb51c",
            false
         ],
         [
            "87a247",
            false
         ]
      ],
      "side":"Islands Fries",
      "silverware":"None"
   },
   {
      "itemName":"Side Slaw",
      "cat":"side",
      "ingredients":[
         [
            "ca9df6",
            false
         ]
      ],
      "side":"None",
      "silverware":"Fork"
   },
   {
      "itemName":"Grilled Mahi Platter",
      "cat":"other",
      "ingredients":[
         [
            "fed439",
            false
         ],
         [
            "161cc5",
            false
         ],
         [
            "1ac532",
            false
         ],
         [
            "dd7267",
            false
         ],
         [
            "f99fb1",
            false
         ],
         [
            "d69389",
            false
         ]
      ],
      "side":"None",
      "silverware":"Knife\/Fork"
   },
   {
      "itemName":"Side Pineapple Skewer",
      "cat":"side",
      "ingredients":[
         [
            "c87bb5",
            false
         ],
         [
            "846e95",
            false
         ]
      ],
      "side":"None",
      "silverware":"None"
   },
   {
      "itemName":"Side Rings",
      "cat":"side",
      "ingredients":[
         [
            "af4868",
            false
         ]
      ],
      "side":"None",
      "silverware":"None"
   },
   {
      "itemName":"Charge Rings",
      "cat":"side",
      "ingredients":[
         [
            "c09931",
            false
         ]
      ],
      "side":"None",
      "silverware":"None"
   },
   {
      "itemName":"Side Apples",
      "cat":"side",
      "ingredients":[
         [
            "48874a",
            false
         ],
         [
            "846e95",
            false
         ]
      ],
      "side":"None",
      "silverware":"None"
   },
   {
      "itemName":"Side Broccoli",
      "cat":"side",
      "ingredients":[
         [
            "618b1e",
            false
         ]
      ],
      "side":"None",
      "silverware":"None"
   },
   {
      "itemName":"Side Salad",
      "cat":"side",
      "ingredients":[
         [
            "ba57e8",
            false
         ],
         [
            "55e848",
            false
         ],
         [
            "b2612d",
            false
         ],
         [
            "f21f47",
            false
         ],
         [
            "39d862",
            false
         ]
      ],
      "side":"None",
      "silverware":"Chilled Fork"
   },
   {
      "itemName":"Tortilla Soup",
      "cat":"other",
      "ingredients":[
         [
            "eb5133",
            false
         ],
         [
            "9f75e2",
            false
         ],
         [
            "df7bdd",
            false
         ],
         [
            "b482e5",
            false
         ],
         [
            "dbf5b9",
            false
         ]
      ],
      "side":"None",
      "silverware":"Spoon"
   },
   {
      "itemName":"Side Caesar",
      "cat":"side",
      "ingredients":[
         [
            "cd8481",
            false
         ],
         [
            "964192",
            false
         ],
         [
            "f21f47",
            false
         ],
         [
            "c4c052",
            false
         ]
      ],
      "side":"None",
      "silverware":"Chilled Fork"
   },
   {
      "itemName":"Side Soup",
      "cat":"side",
      "ingredients":[
         [
            "eb5133",
            false
         ],
         [
            "9f75e2",
            false
         ],
         [
            "df7bdd",
            false
         ],
         [
            "b482e5",
            false
         ]
      ],
      "side":"None",
      "silverware":"Spoon"
   },
   {
      "itemName":"Steamed Veggies",
      "cat":"side",
      "ingredients":[
         [
            "c0659c",
            false
         ],
         [
            "55e848",
            false
         ],
         [
            "9c7ad5",
            false
         ],
         [
            "eede9b",
            false
         ]
      ],
      "side":"None",
      "silverware":"Fork"
   },
   {
      "itemName":"Side Ranchero Beans",
      "cat":"side",
      "ingredients":[
         [
            "75dbfa",
            false
         ],
         [
            "569128",
            false
         ]
      ],
      "side":"None",
      "silverware":"None"
   }
];